version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "EVENT-TOPIC"
  kafkaviewer:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - "9003:9000"
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKERCONNECT: localhost:9092
      SERVER_SERVLET_CONTEXTPATH: /