version: '3'
services:
#  web:
#    environment:
#      - PROFILE=integration
#      - RATER_DB_HOST=db
#      - RATER_DB_NAME=rater
#    depends_on:
#      - db
#      - zookeeper
#      - kafka
#    links:
#      - "db"
#      - "zookeeper"
#      - "kafka"
#    image: bdinnovations/flo-rater:latest
#    ports:
#      - "8080:8442"
#      - "5701:5701"
#    expose:
#      - "8080"
#      - "5701"
  db:
    image: postgres:12.2
    container_name: t_mates_db
    shm_size: 1gb
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - rater_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mcadmin
      POSTGRES_PASSWORD: mcadmin
      POSTGRES_DB: t_mates
    command:
      - "postgres"
      - "-c"
      - "max_connections=350"
      - "-c"
      - "shared_buffers=2GB"
      - "-c"
      - "wal_level=logical"
    #      - "-c"
    #      - "log_statement=all"
  zookeeper:
    image: 'bitnami/zookeeper:3.6.1'
    hostname: zookeeper
    ports:
      - '2181:2181'
    expose:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2.5.0'
    hostname: kafka
    ports:
      - '9092:9092'
    links:
      - "zookeeper"
    expose:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_RETENTION_HOURS=3
      - KAFKA_LOG_ROLL_HOURS=1
    volumes:
      - 'kafka_data:/bitnami'
    depends_on:
      - zookeeper

  kafkaviewer:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - "9003:9000"
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181.
      - KAFKA_BROKERCONNECT=kafka:9092
      - SERVER_SERVLET_CONTEXTPATH=/

#  hazelcast-management-center:
#    image: hazelcast/management-center:4.0.3
#    ports:
#      - 8100:8080
volumes:
  rater_dbdata:
    external: false
  kafka_data:
    external: false